CREATE TABLE IF NOT EXISTS books(mode TEXT PRIMARY KEY CHECK(mode IN ('demo','live')),revision INTEGER NOT NULL,payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS requests(mode TEXT NOT NULL, id TEXT NOT NULL, fingerprint TEXT NOT NULL, PRIMARY KEY(mode,id));
CREATE TABLE IF NOT EXISTS usage(id INTEGER PRIMARY KEY, provider TEXT NOT NULL, at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS usage_window ON usage(provider,at);
CREATE TABLE IF NOT EXISTS imports(token TEXT PRIMARY KEY, mode TEXT NOT NULL, revision INTEGER NOT NULL, payload TEXT NOT NULL, expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS leases(name TEXT PRIMARY KEY, until_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS boss_analyses(character_id TEXT PRIMARY KEY, checked_at INTEGER NOT NULL, payload TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS credentials(id INTEGER PRIMARY KEY CHECK(id=1), encrypted TEXT NOT NULL, fingerprint TEXT NOT NULL, account_signature TEXT NOT NULL, verified_at TEXT NOT NULL, generation INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS connection_lock(id INTEGER PRIMARY KEY CHECK(id=1), generation INTEGER NOT NULL DEFAULT 0);
INSERT OR IGNORE INTO connection_lock(id,generation) VALUES(1,0);
DELETE FROM books WHERE mode='demo';
DELETE FROM requests WHERE mode='demo';
DELETE FROM imports WHERE mode='demo';
